x = "5"
local y = tonumber(x)
print(y, type(y))
print(5 + 5)
print(5 - 5)
print(5 * 5)
print(5 ^ 5)
print(5 / 5)
print(5 // 5 )
print(5 % 5)
print(10 / 2.5)
print(math.pi)

math.randomseed(os.time())
local random = math.random()
local defined_random = math.random(10)
local well_defined_random = math.random(10, 20)
print(random)
print(defined_random)
print(well_defined_random)
print(math.floor(math.pi))
print(math.ceil(math.pi))
